select * from customer limit 4;

-- --Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount)as Total_Revenue from customer
group by gender;

-- --Q 2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer
where discount_applied='YES' and purchase_amount > (select avg(purchase_amount) from customer);

-- --Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) avg_rating from customer
group by item_purchased
order by avg_rating desc limit 5;

-- --Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, avg(purchase_amount)as Avg_purchase_amount from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type;

-- --Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, count(customer_id) as No_of_Customer, avg(purchase_amount) as avg_purchase_amount, sum(purchase_amount) as Total_Revenue from customer
group by subscription_status;

-- --Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100*sum(case when discount_applied='YES' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- --Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment;
with customer_type as(select *,
case
     when previous_purchases=1 then 'New'
     when previous_purchases between 1 and 10 then 'Returning'
     else 'Loyal'
     end as 'Segment'
from customer) 
select segment, count(*) "Number of Customer" from customer_type
group by segment;

-- --Q8. What are the top 3 most purchased products within each category?
with item_count as(
select category, item_purchased, count(customer_id)as total_order,
row_number() over(partition by category order by count(customer_id) desc)as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_order from item_count
where item_rank<4;

-- --Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer
where previous_purchases >5
group by subscription_status;


-- --Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount)as Revenue_by_Age_Group from customer
group by age_group
order by Revenue_by_Age_Group desc